name: apptive_grid_error_reporting
description: An error reporting tool using ApptiveGrid to send/store error reports
version: 0.1.1
homepage: https://www.apptivegrid.de
repository: https://github.com/ApptiveGrid/ApptiveGrid-flutter-dev-tools/tree/main/packages/apptive_grid_error_reporting

environment:
  sdk: ">=3.0.0 <4.0.0"

  flutter: ">=1.17.0"

dependencies:
  apptive_grid_core: ^2.1.1

  collection: ^1.17.2
  flutter:
    sdk: flutter
  http: '>=0.13.6 <2.0.0'
  package_info_plus: '>=4.0.0 <6.0.0'
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.1
