name: apptive_grid_error_reporting
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  http: ^1.1.0

dependencies:
  apptive_grid_core: ^1.7.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  package_info_plus: ^1.4.2
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
